#Manually removed - upgrade
#require_relative '../node_modules/react-native/scripts/react_native_pods'
#require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

#Manually added  - upgrade
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

#recheck - to be modified
platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

#recheck - if to be added
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green


target 'KidsSketchToStories' do
  config = use_native_modules!

   #Manually removed - upgrade 
  # Flags change depending on the env values.
  #flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  #recheck
  target 'KidsSketchToStoriesTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    #__apply_Xcode_12_5_M1_post_install_workaround(installer)   #//Manually removed - upgrade
  end
end
